### ISSUE TITLE
server(configuration, settings) error 

### ISSUE THREAD

**Issue by xiyuyizhi** [catamphetamine/universal-webpack#89]
my project used create-react-app,and i eject the config files

i create webpack.config.client.babel.js as follow

```


const { server } = require('universal-webpack/config')
const settings = require('./universal-webpack-settings')
const configuration = require('./webpack.config.prod') //the production config  by create-react-app
module.exports = server(configuration, settings)
```

when run `webpack --config './config/webpack.config.server.babel.js'`

i get the error

```
/Users/xiyuyizhi/gitServer/movies/fe/node_modules/universal-webpack/build/loaders.js:202            
                                throw _iteratorError3;                                              
                                ^                 

TypeError: rule.loader.split is not a function    
    at normalize_rule_loaders (/Users/xiyuyizhi/gitServer/movies/fe/node_modules/universal-webpack/source/loaders.js:162:29)
    at normalize_configuration_rule_loaders (/Users/xiyuyizhi/gitServer/movies/fe/node_modules/universal-webpack/source/loaders.js:128:3)
    at server_configuration (/Users/xiyuyizhi/gitServer/movies/fe/node_modules/universal-webpack/build/server configuration.js:120:52)
    at Object.<anonymous> (/Users/xiyuyizhi/gitServer/movies/fe/config/webpack.config.server.babel.js:7:18)
    at Module._compile (module.js:569:30)         
    at loader (/Users/xiyuyizhi/gitServer/movies/fe/node_modules/babel-register/lib/node.js:144:5)  
    at Object.require.extensions.(anonymous function) [as .js] (/Users/xiyuyizhi/gitServer/movies/fe/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)             
    at tryModuleLoad (module.js:466:12)           
    at Function.Module._load (module.js:458:3)    
    at Module.require (module.js:513:17)          
    at require (internal/module.js:11:18)         
    at requireConfig (/Users/xiyuyizhi/gitServer/movies/fe/node_modules/webpack/bin/convert-argv.js:96:18)
    at /Users/xiyuyizhi/gitServer/movies/fe/node_modules/webpack/bin/convert-argv.js:109:17         
    at Array.forEach (native)                     
    at module.exports (/Users/xiyuyizhi/gitServer/movies/fe/node_modules/webpack/bin/convert-argv.js:107:15)
```

**Comment by catamphetamine** [comment]
Post your webpack config.
Seems that `universal-webpack` can't parse some of its rules.

**Comment by catamphetamine** [comment]
Or, alternatively, you could open `(/Users/xiyuyizhi/gitServer/movies/fe/node_modules/universal-webpack/source/loaders.js:162:29)` in an editor and add `console.log(rule)` to see what it outputs before throwing the error.

**Comment by catamphetamine** [comment]
So, `rule.loader.split is not a function` means that `rule.loader` is not a string.
As far as I'm aware `rule.loader` can only be a string, so it's most likely an error in your webpack config.

**Comment by catamphetamine** [comment]
From Webpack docs:
https://webpack.js.org/configuration/module/#useentry

> It must have a loader property being a string. It is resolved relative to the configuration context with the loader resolving options (resolveLoader).

**Comment by xiyuyizhi** [comment]
@catamphetamine   the webpack config i used [https://github.com/xiyuyizhi/movies/blob/redux-redux-saga/fe/config/webpack.config.prod.js](url)

**Comment by catamphetamine** [comment]
Try adding `console.log(rule)` to `node_modules/build/loaders.js` before `rule.loader.split('!')` and see what does it output.
https://unpkg.com/universal-webpack@0.6.0/build/loaders.js
